spring:
    name: crm-account-service
    
    
    
    
### LOGGING ##
logging:
    charset: file
    config: file://${user.home}/crm-logs
    exception-conversion-word: '%wEx'
    file:
        name: crmlogs
        path: /home/wanjohi/crm-logs
    group: '*'
    level: '*'
    logback:
        rollingpolicy:
            clean-history-on-start: false
            file-name-pattern: ${LOG_FILE}.%{yyyy-MM-dd}.%i.gz #Pattern for rolled-over log file names.
            max-file-size: 10MB #Maximum log file size.
    pattern:
        console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}' #Appender pattern for output to the console. Supported only with the default Logback setup.
