spring:
    name: crm-account-service
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/crm_account_service_db
        username: root
        password: 12345678
    jpa:
        hibernate: 
            ddl-auto: update
    
    
    
    
### LOGGING ##
logging:
    charset: file
    config: file://${user.home}/crm-logs
    exception-conversion-word: '%wEx' #Conversion word used when logging exceptions.
    file:
        name: crmlogs #Log file name (for instance, `myapp.log`). Names can be an exact location or relative to the current directory.
        path: /home/wanjohi/crm-logs
    group: '*' #Log groups to quickly change multiple loggers at the same time. For instance, `logging.group.db=org.hibernate,org.springframework.jdbc`
    level: '*' # Log levels severity mapping. For instance, `logging.level.org.springframework=DEBUG`.
    logback:
        rollingpolicy:
            clean-history-on-start: false
            file-name-pattern: ${LOG_FILE}.%{yyyy-MM-dd}.%i.gz #Pattern for rolled-over log file names.
            max-file-size: 10MB #Maximum log file size.
    pattern:
        console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}' #Appender pattern for output to the console. Supported only with the default Logback setup.
